### ISSUE TITLE
(Chore)Reading documentation of necessary libraries

### ISSUE THREAD

**Issue by alchemist09** [ALCHEMIST09/bc-9-matlab#1]
Reading through documentations of necessary libraries such as cmd to get acquainted on how to include them in the project source files

**Comment by andela-anandaa** [comment]
My advice here will be, you can just jump first into designing your application. The CLI libraries are basically just wrappers on top of your main implementation.

Perhaps, I would like to see a sort of design of how you want to implement your solution.

**Comment by alchemist09** [comment]
Since you and Chidi specified we were not to use libraries such as
prompt_toolkit and pyparse like was done with members of previous
bootcampers, we had to alter the logical design of how the application was
going to work by being able to parse input from the user using string
functions and regex. Attached is a simple design of how I'm going to design
the application
