### ISSUE TITLE
(chore)Installing necessary libraries

### ISSUE THREAD

**Issue by alchemist09** [ALCHEMIST09/bc-9-matlab#2]
After familiarizing myself with the dependent libraries, I proceed on to install them on my system, and add any required configurations

**Comment by andela-anandaa** [comment]
I see this as the only thing on _Current_, is this the only thing you want to achieve today?

**Comment by alchemist09** [comment]
The project had quite a number of complexities, of which you can even
confirm with Chidi, which he too acknowledged, but we reached a conclusion
on the implementation
